mssql.dbinit.container = true

# databaseType:oracle | mssql
intershop.databaseType=mssql

# with local dbinit
intershop.db.mssql.url=jdbc:sqlserver://machine.tools.intershop.com:1433
intershop.db.mssql.sa.password = 1ntershop5A
intershop.db.mssql.dbname=icmtestdb

intershop.jdbc.url=jdbc:sqlserver://machine.tools.intershop.com:1433;databaseName=icmtestdb
intershop.jdbc.mssql.url=jdbc:sqlserver://machine.tools.intershop.com:1433;databaseName=icmtestdb
intershop.jdbc.mssql.url.master=jdbc:sqlserver://machine.tools.intershop.com:1433;databaseName=master
# intershop.jdbc.url=jdbc:oracle:thin:@localhost:1521:XE

intershop.jdbc.user=intershop
intershop.jdbc.password=intershop

intershop.jdbc.mssql.dba.url=${intershop.jdbc.mssql.url.master}
intershop.jdbc.mssql.dba.user=sa
intershop.jdbc.mssql.dba.password=${intershop.db.mssql.sa.password}

# staging test properties
intershop.jdbc.mssql.live.name=livetest
intershop.jdbc.mssql.live.login=livetestlogin
intershop.jdbc.mssql.live.user=livetestlogin
intershop.jdbc.mssql.live.url=${intershop.db.mssql.url};databaseName=livetest

intershop.jdbc.mssql.testedit.name=edittest
intershop.jdbc.mssql.testedit.login=edittestlogin
intershop.jdbc.mssql.testedit.user=edittestlogin
intershop.jdbc.mssql.testedit.url=${intershop.db.mssql.url};databaseName=edittest

intershop.jdbc.mssql.testedit.linkName=localhost
intershop.jdbc.mssql.testedit.sourceDBLink=localhost.edittest.dbo

# webserver etc.
intershop.WebServerURL = http://machine.tools.intershop.com:8080
intershop.WebServerSecureURL = https://machine.tools.intershop.com:8443

intershop.local.hostname = machine.tools.intershop.com

mail.smtp.host=host.localdev.intershop.com
mail.smtp.port=25

intershop.SMTPServer=machine.tools.intershop.com
intershop.mail.messageID.domain=responsive

webServer.cert.path = /home/intershop/ssl
webserver.cert.server = tools.intershop.com.crt
webserver.cert.privatekey = tools.intershop.com.key

intershop.db.readinessProbe.interval = 5
intershop.db.readinessProbe.timeout = 120

# necessary for automatic Solr resest
intershop.smc.admin.user.name = admin
intershop.smc.admin.user.password = !InterShop00!
disable.ssl.verification = true