Class1 = com.intershop.beehive.core.dbmigrate.preparer.preference.AddPreferenceDefinitionsPreparer \
         com.intershop.application.test.dbinit.data.preference.PreferenceDefinitions \
         com.intershop.application.test.dbinit.data.preference.PreferenceDefinitionInformation \
         com/intershop/application/responsive/dbmigrate/data/54.0.1/preference/PreferenceDefinitionUUIDs.properties
       
         